### ISSUE TITLE
Кейсы

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#1]
Страница кейсы на iphone 4s - гамбургер не работает https://yadi.sk/d/kfIHKR4s3Eqdus

**Comment by nicothin** [comment]
@w365r 
Перекрыт временным блоком со списком всех готовых страниц.
Исправлено.

**Comment by w365r** [comment]
:-) 
теперь при нажатии на гамбургер открывается меню, но при открытии меню и нажатии на пустое поле справа от ссылок открывается временный блок

**Comment by nicothin** [comment]
@w365r 
убрал этот служебный блок вообще.
https://github.com/nicothin/w365/issues/10  ссылки на все страницы
