### ISSUE TITLE
Кнопки CTA на моб устройствах

### ISSUE THREAD

**Issue by WEB365ru** [nicothin/w365#11]
В адаптивной версии сайта все кнопки Call to action (которые вызывают различные формы связи и т.д.) – скрыты. Остаются лишь кнопки, ведущие на другие страницы, а так же ссылки. (Из спецификации)

**Comment by w365r** [comment]
Дополню: есть кнопки в тексте, открывающие формы обратной связи (на мобилке нужно скрыть) и кнопка связаться с нами (которой нет на десктопе, прилеплена к нижнему краю) - она просто ведет на страницу контакты

**Comment by nicothin** [comment]
для мобилки
Разработка вебсайтов: убрал кнопки Задать вопрос
Адаптация: убрал кнопки Заказать
Поддержка: убрал все кнопки
Дизайн: убрал кнопки
Аналитика: убрал кнопки
Поисковое: убрал кнопки
Таргетированная: убрал кнопку
Медийная: убрал кнопку

**Comment by w365r** [comment]
теперь все ок
