### ISSUE TITLE
Анимация

### ISSUE THREAD

**Issue by WEB365ru** [nicothin/w365#12]
Просьба сделать анимацию появления элементов после загрузки страниц сделать плавнее и нелинейной

**Comment by nicothin** [comment]
@WEB365ru 
поясните про «плавнее» — в каких браузерах и ОС и что именно «дергается»?

**Comment by WEB365ru** [comment]
По поводу "Плавнее": технически все реализовано четко, но визуально все элементы появляются очень резко и быстро. Возможно попробовать достичь плавности за счет того, что ее немного замедлить. Так же сама анимация (имеется ввиду именно появление элементов после загрузки страниц) кажется линейной, что противоречит материал-дизайну. В ТЗ есть пара примеров как это должно примерно выглядеть. 
Браузеры - Хром (пробовали на нескольких версиях), Яндекс
ОС - так же пробовали на нескольких

**Comment by nicothin** [comment]
@WEB365ru сделал для главной страницы (если так нормально, добавлю и другим)
- медленнее
- двигающиеся фрагменты имеют прозрачность в начале анимации (и до 30% ее длительности)
- сменил тайм-функцию (доабил более заметное замедление к концу анимации

**Comment by WEB365ru** [comment]
По анимации все ок, но вылез баг - на разр. 1920 пропадает буква W и размываются пункты меню (скриншот скинул ВК)

Браузеры - те же, ОС тоже на неск разных пробовали

**Comment by nicothin** [comment]
@WEB365ru исправлено
сейчас поменяю анимации на прочих страницах

**Comment by WEB365ru** [comment]
ок, спасибо)

**Comment by nicothin** [comment]
@WEB365ru 
сделал медленнее и менее линейной анимацию для контентных страниц
кое-где (кнопка Обсудить, Лого, Заголовок) добавил в начало анимации прозрачность.
