### ISSUE TITLE
Пропадает первый экран при разворачивании меню обсудить проект

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#15]
На страницах поддержка сайта, разработка сайта и других, где более 1 экрана, при разворачивании меню обсудить проект на первом экране он пропадает. Помогает повторное разворачивание/сворачивание на последнем экране или обновление страницы:

до https://yadi.sk/i/ir7Z7CrU3F6dTi
после https://yadi.sk/i/WazEuG5I3F6dVi

Николай, после исправления прошу сказать что конкретно правили, т.к. планировали выложить статичную версию сайта и внесли текст прямо в верстку.

**Comment by nicothin** [comment]
@w365r 
исправлено.
https://raw.githubusercontent.com/nicothin/w365/84b3f8e1cab4befb87eff3b98591642c47cc52eb/js/script.min.js — менял только этот JS-файл. Его нужно сохранить в проект как `js/script.min.js` (с заменой).

**Comment by w365r** [comment]
теперь все ок, спасибо
