### ISSUE TITLE
При добавлении кейсов едет верстка

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#16]
При добавлении кейсов расстояние между элементами карусели меняется в меньшую стороны и начинает ехать верстка https://yadi.sk/i/X1J_7sQm3F6fVm

**Comment by nicothin** [comment]
@w365r 
добавляю в верстке — ничего не едет: http://take.ms/V7Ugt
дайте ссылку на страницу с проблемой, нужно разобраться с ней «вживую».

**Comment by w365r** [comment]
Вот это значение рассчитывается автоматически https://yadi.sk/i/kZxjP4mv3F7ZBF
При добавлении новых кейсов в верстку и изменении параметра их количества в конфиге https://yadi.sk/i/-KwfuXDB3F7ZW9 значение меняется на меньшее.

**Comment by w365r** [comment]
это становится заметно только при добавлении разных картинок под каждый кейс, т.к. если количество кейсов в html больше, чем указанное в конфиге карусель начинает показывать не ту картинку, которая привязана к названию проекта.

**Comment by nicothin** [comment]
Баз живой страницы я не смогу ничего сделать, в любом случае.

**Comment by nicothin** [comment]
количество в конфиге менять не нужно. если поменять — рассчетный размер изменится.
думаю, проблема в этом.
не меняйте ничего в компилируемых файлах — в JS и в CSS.

**Comment by w365r** [comment]
вот архив, нужно смотреть в папке cases https://yadi.sk/d/C6wLahoU3F7apy

**Comment by w365r** [comment]
Вернул значение в конфиге js для количества кейсов, добавил в файл cases/index.html еще кейсы. При прокрутке обратите внимание, что в браузере для проекта отображается не та картинка, которая указана в html. Изменение конфига проблему решает, но меняется высота блока.
Другими словами, сейчас нельзя добавить больше 5 кейсов.

**Comment by nicothin** [comment]
@w365r глюк в верстке повторил, сейчас разберусь.
В любом случае, JS и CSS — компилируемые файлы, не меняйте их вручную.

**Comment by nicothin** [comment]
https://nicothin.github.io/w365/cases.html — протестировал, работает корректно (добавил цифры, чтобы точно сопоставить две карусели).
Для внедрения изменений замените `js/script.min.js` на исправленный: https://raw.githubusercontent.com/nicothin/w365/gh-pages/js/script.min.js

**Comment by nicothin** [comment]
p.s.
`items` в том скрипте — кол-во одновременно видимых пунктов в списке, с кол-вом слайдов не связано.

**Comment by w365r** [comment]
спасибо, заработало
