### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#2]
iphone 4s - кнопка наезжает на лого https://yadi.sk/d/kfIHKR4s3Eqdus

**Comment by w365r** [comment]
+ гамбургер также не работает - отображается как в кейсах

**Comment by nicothin** [comment]
@w365r 
Бургер был перекрыт временным блоком со списком всех готовых страниц.
Исправлено.

По скрину неясно о какой кнопке речь. Уточните.

**Comment by w365r** [comment]
кнопка связаться с нами https://yadi.sk/i/ocywhjPE3ErRDV

**Comment by nicothin** [comment]
исправлено
