### ISSUE TITLE
Гамбургер на смартфоне

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#3]
На iphone 4s всех страницах при нажатии на гамбургер открывается не так, как в дизайне (см. скрин в issue про главную и кейсы)

**Comment by nicothin** [comment]
@w365r 
В ТЗ не вижу данных о анимациях для мобильной версии.
В макетах их тоже нет.
Как должно быть?

**Comment by w365r** [comment]
сорри, я имел ввиду не анимацию, а временный список страниц, который открывается при нажатии на пустое поле
