### ISSUE TITLE
Попапы

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#4]
На всех страницах нет попапов для кнопока заказать, связаться с нами, задать вопрос

**Comment by nicothin** [comment]
@w365r 
В ТЗ об этом нет данных
В макетах попапы есть только для контактов.
О каких попапах речь?

**Comment by w365r** [comment]
при нажатии на кнопки на декстопе должны открываться попапы как на странице контакты по кнопке заказать звонок

**Comment by nicothin** [comment]
@w365r 
сделал не только на десктопе, т.к. не указано действие на мобилке
сделал для заказать, заказать [что-то] и для Задать вопрос
для Связаться с нами не сделал, т.к. они на десктопе не видны никогда, только мобильные

**Comment by w365r** [comment]
На десктопе теперь такая проблемка https://yadi.sk/i/zy318IYa3Et7xC

**Comment by nicothin** [comment]
исправлено
