### ISSUE TITLE
Нет валидации данных на формах

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#5]
1. В поле номера телефона можно ввести любые символы https://yadi.sk/i/dKGNcJK43ErRV2

2. В контактах по кнопке написать нам человек вводит не номер телефона, а email https://yadi.sk/i/dh2OaNZW3ErSSH

**Comment by nicothin** [comment]
@w365r 
сделал проверки с уровня html. 
прошел по всем формам, вписал обязательность заполнения и ожидаемый в поле паттерн (проверяется браузером перед отправкой).
это IE10+, может не работать в других старых браузерах.
в поле телефона нужна возможность вводить любые символы (но отправка формы возможна только при корректном вводе)

полноценное JS-валидирование не предусмотрено в ТЗ, не учитывалось при ценообразовании, бесплатно сделать не могу (долго).

**Comment by w365r** [comment]
понятно, доделаем своими силами

**Comment by nicothin** [comment]
Убрал с полей для телефонов проверку по паттерну, т.к. на всех них теперь включено маскирование номера телефона и со включенным JS там при всем желании ничего кроме телефона не ввести.
