### ISSUE TITLE
На странице контакты мутная картинка слева

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#6]
Сравнение макета и верстки: https://yadi.sk/i/WrDTfEg43ErSin

**Comment by nicothin** [comment]
@w365r 
Сделано для уменьшения веса (по причине вторичности этого изображения), согласовывалось с Владимиром.
Менять?

**Comment by w365r** [comment]
Да, сделайте, пожалуйста, качественнее (сейчас 132 кб, можно поднять до 500-750 кб). Спасибо.

**Comment by nicothin** [comment]
@w365r 
сделано

![okay](http://uploads.neatorama.com/images/posts/114/82/82114/1433129672-0.jpg)
