### ISSUE TITLE
Обсудить проект

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#8]
При 1920х1080 есть вертикальный скролл (при том, что форма на пол экрана) https://yadi.sk/i/5Z2siIuO3ErTnt

При меньше разрешении скролла нет  https://yadi.sk/i/b_7NcLjc3ErUGg

Прошу убрать скролл с этой формы.

Также нет валидации номера телефона. Можно сделать маску как тут http://www.iq-spb.com при нажатии на поле ввода номера по кнопке заказать звонок  https://yadi.sk/i/RJ9hudm53ErUaF

**Comment by nicothin** [comment]
Форму сделал немного компактнее, выравниваю по верт. центру блока с белым фоном.
На высоте вьюпорта менее 910 скролл будет  не влезет по высоте.
Маску телефона добавил.
