### ISSUE TITLE
Контакты на мобиле

### ISSUE THREAD

**Issue by w365r** [nicothin/w365#9]
iphone 4s , на странице контакты кнопка _позвонить_ не входит на экран и страница вертикально не скроллится

**Comment by w365r** [comment]
https://yadi.sk/d/DUNPJsuf3EteqY

**Comment by w365r** [comment]
(скриншоты смотреть в полный экран)

**Comment by nicothin** [comment]
Поправил, прошу глянуть.

**Comment by w365r** [comment]
Попробовал в приватном окне - также

**Comment by nicothin** [comment]
возможно, не задеплоилось еще на момент проверки
сейчас должно уже задеплоиться

**Comment by w365r** [comment]
также

**Comment by nicothin** [comment]
![image](https://cloud.githubusercontent.com/assets/3499680/23543738/a4c2bc44-0004-11e7-8ba0-2eb30f33771c.png)

ну теперь-то точно уже не может быть такого скрина с проблемой.
вон, даже на высоте вьюпорта 350px все влезает.

**Comment by w365r** [comment]
да, теперь ок
